/*
 * PKHub API
 *
 * Retrieve group secrets, logins, envs ....
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Db struct {

	Lbl string `json:"lbl"`

	Type_ string `json:"type,omitempty"`

	HostedOn string `json:"hosted-on,omitempty"`

	Host string `json:"host,omitempty"`

	Port string `json:"port,omitempty"`

	Database string `json:"database,omitempty"`

	Dbuser string `json:"dbuser,omitempty"`

	Password string `json:"password,omitempty"`
}
