/*
 * PKHub API
 *
 * Retrieve group secrets, logins, envs ....
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Login struct {

	Lbl string `json:"lbl,omitempty"`

	Login string `json:"login,omitempty"`

	UserName string `json:"user-name,omitempty"`

	UserName2 string `json:"user-name2,omitempty"`

	Secret string `json:"secret,omitempty"`
}
