/*
 * PKHub API
 *
 * Retrieve group secrets, logins, envs ....
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Snippet struct {

	Title string `json:"title"`

	Val string `json:"val,omitempty"`
}
